export const getAuthUrl = () => '/auth'
export const getCategoriesUrl = () => '/categories'
export const getReviewsUrl = () => '/reviews'
export const getUsersUrl = () => '/users'
export const getOrdersUrl = () => '/orders'
export const getStatisticsUrl = () => '/statistics'
export const getPaymentUrl = () => '/payment'
export const getProductsUrl = () => '/products'